---
title: "巴西購物嘉年華"
author: "Group6-楊禾馨"
date: "2019/4/12"
output: html_document
---

<hr>
```{r}
#pkgs=c("dplyr",ggplot2","lubridate","stringr")
pacman::p_load(dplyr,ggplot2,lubridate,stringr)
```

```{r}
customers=read.csv("~/Desktop/R/olist_customers_dataset.csv")
location=read.csv("~/Desktop/R/olist_geolocation_dataset.csv")
item=read.csv("~/Desktop/R/olist_order_items_dataset.csv")
payments=read.csv("~/Desktop/R/olist_order_payments_dataset.csv")
reviews=read.csv("~/Desktop/R/olist_order_reviews_dataset.csv")
orders=read.csv("~/Desktop/R/olist_orders_dataset.csv")
products=read.csv("~/Desktop/R/olist_products_dataset.csv")
sellers=read.csv("~/Desktop/R/olist_sellers_dataset.csv")
pname=read.csv("~/Desktop/R/product_category_name_translation.csv")
```
<hr>
###合併產品名欄位
```{r}
products=merge(products,pname, by="product_category_name") 
products=products[-c(1)]
```
<hr>
###整理日期資料
```{r}
purchase_month<-substr(orders$order_purchase_timestamp,6,7)
ym<-substring(orders$order_purchase_timestamp,1,7)
orders=cbind(orders,purchase_month,ym) 
```

<hr>
```{r} 
ggplot(orders,aes(factor(ym)))+
  geom_bar(fill='lavenderblush3',width =1,color='seashell4')+ 
  coord_flip()+ 
  labs(x='',y='')+ 
  theme_bw() +
  theme(panel.grid =element_blank())
```

<hr>
```{r}
c=table(orders$ym)
plot(c,type="l",ylab="")
```


<hr>
###Merge"item"to"item_plus"
```{r} 
item_plus=merge(item,orders, by="order_id") 
item_plus=merge(item_plus,products,by="product_id") 
item_plus=item_plus[c(1,2,4,8,15,16,24)] 
names(item_plus)[7]<-paste("product_name") 
```

<hr>
###Heatmap:Month&Product
```{r}
month_detail<-ggplot(item_plus,aes(x=purchase_month,y=product_name))
month_detail+stat_bin2d()+
scale_fill_gradient(low="lightblue",high="red",limits=c(0,1500))+
#設置顏色過渡爲從淺藍到紅色，對應區間爲0-1500，table得出最高單項銷量不超過1200
labs(x='Month',y='Product')+
theme_bw()+
theme(axis.text.y= element_text(size =6, vjust = 0.5, hjust =1))+
theme(panel.grid =element_blank())
```


<hr>
```{r}
tail(sort(summary(sellers$seller_state))) #買家數量最多的前六個州
```

```{r}
tail(sort(summary(customers$customer_state))) #顧客數量最多的前六個州
```

###Merge item_plus
<hr>
```{r}
item_plus<-merge(item_plus,sellers, by="seller_id")
item_plus<-merge(item_plus,customers,by="customer_id")
item_plus=item_plus[c(1:7,10,14)]
```

###Seller_state
<hr>
```{r}
ggplot(item_plus,aes(factor(seller_state)))+
  geom_bar(fill='olivedrab4',width =0.9)+
  coord_flip()+
  labs(x='Sellers',y='')+ 
  theme_bw()+
  theme(panel.grid =element_blank())
```

###Custaomer_state
<hr>
```{r}
ggplot(item_plus,aes(factor(customer_state)))+
  geom_bar(fill='olivedrab4',width =0.9)+ 
  coord_flip()+ 
  labs(x='Customer',y='')+ 
  theme_bw()+ 
  theme(panel.grid =element_blank())
```

###Product & Seller_state
<hr>
```{r}
ggplot()+
  geom_bar(data=item_plus,aes(product_name,fill=seller_state),width=0.9,alpha=0.9)+ 
  coord_flip()+
  labs(x='Product',y='')+ 
  theme(axis.text.y= element_text(size =5, vjust = 0.5))+
  theme_bw()+ 
  theme(panel.grid =element_blank())
```

###Product & Custaomer_state
<hr>
```{r}
ggplot()+
  geom_bar(data=item_plus,aes(product_name,fill=customer_state),width=0.9,alpha=0.9)+ 
  coord_flip()+
  labs(x='Product',y='')+ 
  theme(axis.text.y= element_text(size =5, vjust = 0.5))+
  theme_bw()+ 
  theme(panel.grid =element_blank())
```



<hr>
###Heatmap:Seller_states & Product
```{r}
product_state<-ggplot(item_plus,aes(x=seller_state,y=product_name))
product_state+stat_bin2d()+
scale_fill_gradient(low="lightblue",high="red",limits=c(0,10000))+
#設置顏色過渡爲從淺藍到紅色，對應區間爲0-1500，table得出最高單項銷量不超過10000
theme(text=element_text(family="Heiti TC Light"))+ 
  labs(x='Seller-State',y='Product')+
theme(axis.text.y= element_text(size =6, vjust = 0.5, hjust =1))+
  theme_bw()+ 
theme(panel.grid =element_blank()) 
```
